/**
 * This file was generated by the JPA Modeler
 */
package org.arllaynexpress.modelo;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author ArllayneC
 */
@Entity
public class Pagamento implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String forma_pagamento;

    @Basic
    private String quant_parcelas;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getForma_pagamento() {
        return this.forma_pagamento;
    }

    public void setForma_pagamento(String forma_pagamento) {
        this.forma_pagamento = forma_pagamento;
    }

    public String getQuant_parcelas() {
        return this.quant_parcelas;
    }

    public void setQuant_parcelas(String quant_parcelas) {
        this.quant_parcelas = quant_parcelas;
    }

}
