/**
 * This file was generated by the JPA Modeler
 */
package org.arllaynexpress.modelo;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author ArllayneC
 */
@Entity
public class Voos implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String horario;
    
    @Basic
    private String origem;

    @Basic
    private String destino;

    @OneToMany(targetEntity = Lugar.class)
    private List<Lugar> lugars;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHorario() {
        return this.horario;
    }

    public void setHorario(String horario) {
        this.horario= horario;
    }

    public List<Lugar> getLugars() {
        return this.lugars;
    }

    public void setLugars(List<Lugar> lugars) {
        this.lugars = lugars;
    }

    /**
     * @return the origem
     */
    public String getOrigem() {
        return origem;
    }

    /**
     * @param origem the origem to set
     */
    public void setOrigem(String origem) {
        this.origem = origem;
    }

    /**
     * @return the destino
     */
    public String getDestino() {
        return destino;
    }

    /**
     * @param destino the destino to set
     */
    public void setDestino(String destino) {
        this.destino = destino;
    }

}
